### ISSUE TITLE
Indentation tip

### ISSUE THREAD

**Issue by jericahuang** [meganrofl/prj-rev-bwfs-dasmoto#4]
Your comment about indentation is correct, and it's best practice to keep your code uniformly indented. A great tool to automate this process is dirtymarkup.com and it supports CSS tidying-up as well!

**Comment by meganrofl** [comment]
Thank you for addressing the comment about indentation! I really appreciate the direction, and the awesome tool to put into my 'bag o'tricks'!

**Comment by meganrofl** [comment]
Okay, wow, I just copy/pasted the html into dirtymarkup.com and can really see the difference and benefit of the uniformly indention and also the line breaks are nice! Thanks again
